import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import prettier from 'prettier'
import ts from 'typescript'

/** GENERATED BY IA - CLAUDE CODE **/

const DB_TYPES_DIR = join(__dirname, '../types/db')
const PRETTIER_OPTIONS: prettier.Options = {
  parser: 'typescript',
  singleQuote: true,
  semi: false,
  trailingComma: 'all',
}

function requireEnv(name: string): string {
  const value = process.env[name]
  if (!value) {
    throw new Error(`${name} manquant dans les variables d'environnement.`)
  }
  return value
}

function introspectDatabase(outFile: string): void {
  const url = `postgres://${requireEnv('POSTGRES_USER')}:${requireEnv('POSTGRES_PASSWORD')}@${requireEnv('DB_HOST')}:${requireEnv('DB_PORT')}/${requireEnv('POSTGRES_DB')}`

  execFileSync(
    process.execPath,
    [
      require.resolve('kysely-codegen/dist/cli/bin.js'),
      '--dialect',
      'postgres',
      '--url',
      url,
      '--out-file',
      outFile,
      '--log-level',
      'warn',
    ],
    { stdio: 'inherit' },
  )
}

type TableInterface = {
  name: string
  properties: { name: string; type: string }[]
}

function parseInterfaces(source: string): {
  tables: TableInterface[]
  db: TableInterface
} {
  const sourceFile = ts.createSourceFile(
    'db.ts',
    source,
    ts.ScriptTarget.Latest,
    true,
  )

  const tables: TableInterface[] = []
  let db: TableInterface | undefined

  for (const statement of sourceFile.statements) {
    if (!ts.isInterfaceDeclaration(statement)) continue

    const properties = statement.members
      .filter(ts.isPropertySignature)
      .map(member => ({
        name: member.name.getText(sourceFile),
        type: member.type?.getText(sourceFile) ?? 'unknown',
      }))

    const parsed: TableInterface = { name: statement.name.text, properties }

    if (parsed.name === 'DB') {
      db = parsed
    } else {
      tables.push(parsed)
    }
  }

  if (!db) {
    throw new Error(
      'Interface DB introuvable dans la sortie de kysely-codegen.',
    )
  }

  return { tables, db }
}

async function writeFormatted(
  filePath: string,
  content: string,
): Promise<void> {
  const formatted = await prettier.format(content, PRETTIER_OPTIONS)
  writeFileSync(filePath, formatted)
}

async function writeTableFile(table: TableInterface): Promise<void> {
  const dbTypeName = `${table.name}Db`
  const body = table.properties
    .map(prop => `${prop.name}: ${prop.type}`)
    .join('\n')

  const usesGenerated = table.properties.some(prop =>
    /\bGenerated</.test(prop.type),
  )
  const usesTimestamp = table.properties.some(prop =>
    /\bTimestamp\b/.test(prop.type),
  )

  const imports = [
    usesGenerated ? "import type { Generated } from 'kysely'" : '',
    usesTimestamp ? "import type { Timestamp } from './column-types'" : '',
  ].filter(Boolean)

  const content = `${imports.join('\n')}\n\nexport interface ${dbTypeName} {\n${body}\n}\n`

  await writeFormatted(
    join(DB_TYPES_DIR, `${table.name.toLowerCase()}.ts`),
    content,
  )
}

async function writeColumnTypesFile(tables: TableInterface[]): Promise<void> {
  const usesTimestamp = tables.some(table =>
    table.properties.some(prop => /\bTimestamp\b/.test(prop.type)),
  )
  if (!usesTimestamp) return

  const content = `import type { ColumnType } from 'kysely'\n\nexport type Timestamp = ColumnType<Date, Date | string, Date | string>\n`
  await writeFormatted(join(DB_TYPES_DIR, 'column-types.ts'), content)
}

async function writeDatabaseFile(db: TableInterface): Promise<void> {
  const imports = db.properties
    .map(
      prop =>
        `import type { ${prop.type}Db } from './${prop.type.toLowerCase()}'`,
    )
    .join('\n')
  const body = db.properties
    .map(prop => `${prop.name}: ${prop.type}Db`)
    .join('\n')

  const content = `${imports}\n\nexport type Database = {\n${body}\n}\n`

  await writeFormatted(join(DB_TYPES_DIR, 'database.ts'), content)
}

async function main(): Promise<void> {
  const tmpDir = mkdtempSync(join(tmpdir(), 'kysely-codegen-'))
  const tmpFile = join(tmpDir, 'db.ts')

  try {
    introspectDatabase(tmpFile)
    const source = readFileSync(tmpFile, 'utf-8')
    const { tables, db } = parseInterfaces(source)

    await writeColumnTypesFile(tables)
    await Promise.all(tables.map(writeTableFile))
    await writeDatabaseFile(db)

    console.log(
      `✅ Types générés pour ${tables.length} table(s) dans ${DB_TYPES_DIR}.`,
    )
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }
}

main().catch(err => {
  console.error('❌ Erreur lors de la génération des types DB :', err)
  process.exit(1)
})
